# Generated by Django 4.2.11 on 2024-03-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_meditation_remove_guide_guide_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='system_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Внутренний ID заказа'),
        ),
    ]
