# Generated by Django 4.1.2 on 2024-03-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='course_cost',
            field=models.PositiveIntegerField(null=True, verbose_name='Стоимость покупки курса (руб.)'),
        ),
    ]
