# Generated by Django 4.2.11 on 2024-03-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_options_alter_guide_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='guide_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание гайда'),
        ),
    ]
