# Generated by Django 4.2.11 on 2024-03-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_guide_guide_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_video_file',
        ),
        migrations.AddField(
            model_name='course',
            name='course_link',
            field=models.CharField(max_length=255, null=True, verbose_name='Название видеофайла'),
        ),
        migrations.AddField(
            model_name='course',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_product', to='main.product', verbose_name='Товар'),
        ),
    ]
